spring:
  application:
    name: nacos-discovery-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.0.105:8848/
        username: keroro
        password: keroro
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds2:
          nacos:
            server-addr: 192.168.0.105:8848
            username: nacos
            password: nacos
            data-id: sentinel-${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
server:
  port: 8001